# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0003_auto_20161121_2050'),
        ('GroupsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ManyToManyField(to='ProjectsApp.Project'),
        ),
    ]
