# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b' ', max_length=200, null=True)),
                ('start', models.DateField(default=datetime.date.today, null=True)),
                ('end', models.DateField(default=datetime.date.today, null=True)),
                ('description', models.CharField(default=b' ', max_length=10000, null=True)),
                ('knowledge', models.CharField(default=b' ', max_length=10000, null=True)),
                ('experience', models.CharField(default=b' ', max_length=10000, null=True)),
            ],
        ),
    ]
