# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='endDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='project',
            name='experience',
            field=models.CharField(default=b' ', max_length=100000),
        ),
        migrations.AddField(
            model_name='project',
            name='knowledge',
            field=models.CharField(default=b' ', max_length=10000),
        ),
        migrations.AddField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
