# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 02:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0003_auto_20161119_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default=b' ', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.CharField(default=b' ', max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='knowledge',
            field=models.CharField(default=b' ', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default=b' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
