# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0004_auto_20161119_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.CharField(default=b' ', max_length=10000, null=True),
        ),
    ]
