# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(default=' ', max_length=50, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.CharField(default=' ', max_length=16, null=True)),
                ('about', models.CharField(default=' ', max_length=100000, null=True)),
                ('aboutcomp', models.CharField(default=' ', max_length=100000, null=True)),
                ('projects', models.CharField(default=' ', max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(default=' ', max_length=50, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.CharField(default=' ', max_length=16, null=True)),
                ('about', models.CharField(default=' ', max_length=100000, null=True)),
                ('projects', models.CharField(default=' ', max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(default=' ', max_length=50, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.CharField(default=' ', max_length=16, null=True)),
                ('about', models.CharField(default=' ', max_length=100000, null=True)),
                ('skills', models.CharField(default=' ', max_length=10000, null=True)),
            ],
        ),
    ]
