# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0002_auto_20161121_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='ident',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
