# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0003_auto_20161123_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='projects',
            new_name='classes',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.AddField(
            model_name='engineer',
            name='ident',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='professor',
            name='ident',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
