# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0004_auto_20161123_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='company',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
    ]
