# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0003_auto_20161121_2050'),
        ('CompaniesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='projects',
            field=models.ManyToManyField(to='ProjectsApp.Project'),
        ),
    ]
