# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, null=True, to='ProjectsApp.Project'),
        ),
    ]
