# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0003_auto_20161121_2050'),
        ('AuthenticationApp', '0005_myuser_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='myuser',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='ProjectsApp.Project'),
        ),
    ]
